"""Clean package entrypoints for the freeGP HMC-NUTS workflow."""

from .config import DEFAULT_DTYPE, DEFAULT_SEED, configure_torch
from .data import (
    ReferenceCurves,
    UmbrellaWindow,
    load_reference_curves,
    load_umbrella_windows,
    resolve_dataset_root,
)
from .gp import (
    GibbsKernelConfig,
    JointGPPosterior,
    build_joint_gp,
    build_joint_gp_gibbs,
    gpr_hd,
    gpr_hd_gibbs,
    joint_log_marginal_likelihood,
    joint_loo_loglik,
    predict_derivative,
    predict_function,
    predict_function_mean,
)
from .hmc import (
    HMCChainDiagnostics,
    HyperPriorConfig,
    NUTSConfig,
    display_samples_for_diagnostics,
    run_hmc_nuts,
    sample_posterior_functions,
    stationary_ell_prior_distribution,
    stationary_log_ell_bounds,
    summarize_chain_diagnostics,
)
from .hyperopt import (
    HyperparameterOptimizationResult,
    optimize_stationary_hyperparameters,
)
from .metrics import ReferenceComparison, compare_to_reference_curves
from .preprocess import (
    JointObservations,
    ProcessedUmbrellaData,
    build_joint_observations,
    build_test_grid,
    process_umbrella_windows,
)
from .posterior import (
    HyperposteriorPredictiveSummary,
    anchor_predictive_summary,
    hyperposterior_conditional_means,
    summarize_fixed_posterior_derivative,
    summarize_fixed_posterior_predictive,
    summarize_hyperposterior_derivative,
    summarize_hyperposterior_predictive,
)
from .studies import (
    AblationCell,
    AblationCellResult,
    AblationStudyResult,
    StudyModelConfig,
    run_ablation_study,
    save_ablation_summary,
)
from .workflow import WorkflowBundle, prepare_gprhd_hmc_inputs

__all__ = [
    "AblationCell",
    "AblationCellResult",
    "AblationStudyResult",
    "anchor_predictive_summary",
    "DEFAULT_DTYPE",
    "DEFAULT_SEED",
    "GibbsKernelConfig",
    "HMCChainDiagnostics",
    "HyperPriorConfig",
    "HyperposteriorPredictiveSummary",
    "HyperparameterOptimizationResult",
    "JointGPPosterior",
    "JointObservations",
    "NUTSConfig",
    "ProcessedUmbrellaData",
    "ReferenceComparison",
    "ReferenceCurves",
    "StudyModelConfig",
    "UmbrellaWindow",
    "WorkflowBundle",
    "build_joint_gp",
    "build_joint_gp_gibbs",
    "build_joint_observations",
    "build_test_grid",
    "compare_to_reference_curves",
    "configure_torch",
    "display_samples_for_diagnostics",
    "gpr_hd",
    "gpr_hd_gibbs",
    "joint_log_marginal_likelihood",
    "joint_loo_loglik",
    "load_reference_curves",
    "load_umbrella_windows",
    "optimize_stationary_hyperparameters",
    "predict_derivative",
    "predict_function",
    "predict_function_mean",
    "prepare_gprhd_hmc_inputs",
    "process_umbrella_windows",
    "resolve_dataset_root",
    "run_ablation_study",
    "run_hmc_nuts",
    "save_ablation_summary",
    "summarize_fixed_posterior_predictive",
    "summarize_fixed_posterior_derivative",
    "summarize_chain_diagnostics",
    "summarize_hyperposterior_predictive",
    "summarize_hyperposterior_derivative",
    "hyperposterior_conditional_means",
    "sample_posterior_functions",
    "stationary_ell_prior_distribution",
    "stationary_log_ell_bounds",
]
